from django.contrib import admin
from .models import *

admin.site.register(RouteGuide)
admin.site.register(RouteGuideSegment)
admin.site.register(PersonAndOrganization)
admin.site.register(VerificationRecord)
admin.site.register(MapReference)
admin.site.register(Category)
admin.site.register(Article)
admin.site.register(GeoPath)
admin.site.register(Activity)
admin.site.register(Distance)
admin.site.register(IndicativeDuration)
admin.site.register(RoutePoint)
admin.site.register(AmenityFeature)
admin.site.register(GeoCoordinates)
admin.site.register(RouteGradient)
admin.site.register(RouteDifficulty)
admin.site.register(RouteLegalAdvisory)
admin.site.register(RouteDesignation)
admin.site.register(RouteSegmentGroup)
admin.site.register(UserGeneratedContent)
admin.site.register(Provenance)
admin.site.register(MapImage)
admin.site.register(AccessibilityDescription)
