# Generated by Django 3.0.7 on 2020-06-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAndOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='RouteGuide',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Trackback URL')),
                ('type', models.CharField(default='RouteGuide', max_length=10, verbose_name='@type')),
                ('date_published', models.DateField(blank=True, verbose_name='Date Published')),
                ('date_modified', models.DateField(blank=True, verbose_name='Date Modified')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Is Loop')),
                ('id_as_url', models.URLField(primary_key=True, serialize=False, verbose_name='ID (URL)')),
            ],
        ),
        migrations.CreateModel(
            name='RouteGuideSegment',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Trackback URL')),
                ('type', models.CharField(default='RouteGuide', max_length=10, verbose_name='@type')),
                ('date_published', models.DateField(blank=True, verbose_name='Date Published')),
                ('date_modified', models.DateField(blank=True, verbose_name='Date Modified')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Is Loop')),
                ('id_as_url', models.URLField(primary_key=True, serialize=False, verbose_name='ID (URL)')),
                ('segment', models.IntegerField(verbose_name='Segment Number')),
                ('top_level_route_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteGuide')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateField(verbose_name='Date Verified')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteGuideSegment')),
                ('verified_by', models.ManyToManyField(to='protoroute.PersonAndOrganization', verbose_name='Verified By')),
            ],
        ),
        migrations.CreateModel(
            name='QuantitativeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Distance')),
                ('unit', models.CharField(default='km', max_length=6, verbose_name='Unit')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.AddField(
            model_name='personandorganization',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='protoroute.RouteGuide'),
        ),
        migrations.AddField(
            model_name='personandorganization',
            name='route_guide_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='protoroute.RouteGuideSegment'),
        ),
        migrations.CreateModel(
            name='AccessibilityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteGuideSegment')),
            ],
        ),
    ]
